stages:
  - build
  - test

build:
  image: node:latest
  stage: build
  tags:
    - build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

test:
  image: node:latest
  stage: test
  tags:
    - test
  script:
    - npm install --progress=false
    - npm run test:unit